#!/usr/bin/env bash
set -o errexit -o pipefail

# Load config
source /etc/restic/config

# Set default environment variables
export RESTIC_REPOSITORY="${RESTIC_REPOSITORY}"
export RESTIC_PASSWORD="${RESTIC_PASSWORD}"
export B2_ACCOUNT_ID="${B2_ACCOUNT_ID}"
export B2_ACCOUNT_KEY="${B2_ACCOUNT_KEY}"

# Sleep for a random amount of time
sleep $((${RANDOM} % 300))

# Run backup
${RESTIC_BIN} backup \
    --option b2.connections=10 \
    --files-from /etc/restic/includes.list \
    --exclude-caches \
    --exclude-file /etc/restic/excludes.list \
    --exclude-if-present .restic-ignore
