#!/usr/bin/env bash
set -o errexit -o pipefail

# Load config
source /etc/restic/config

# Set default environment variables
export RESTIC_REPOSITORY="${RESTIC_REPOSITORY}"
export RESTIC_PASSWORD="${RESTIC_PASSWORD}"
export B2_ACCOUNT_ID="${B2_ACCOUNT_ID}"
export B2_ACCOUNT_KEY="${B2_ACCOUNT_KEY}"

# Sleep for a random amount of time
sleep $((${RANDOM} % 300))

# Run backup
${RESTIC_BIN} backup \
    --option b2.connections=10 \
    --files-from /etc/restic/includes.list \
    --exclude-caches \
    --exclude-file /etc/restic/excludes.list \
    --exclude-if-present .restic-ignore

# Prune old backups
${RESTIC_BIN} forget --prune --host "${HOSTNAME}" \
    --keep-last ${KEEP_LAST} \
    --keep-hourly ${KEEP_HOURLY} \
    --keep-daily ${KEEP_DAILY} \
    --keep-weekly ${KEEP_WEEKLY} \
    --keep-monthly ${KEEP_MONTHLY} \
    --keep-yearly ${KEEP_YEARLY}
